selected_features:
- feature_8
- feature_9
- feature_11
- feature_14
- feature_16
- feature_18
- feature_20
- feature_21
- feature_24
- feature_25
- feature_26
- feature_29
- feature_33
- feature_35
- feature_36
- feature_43
- feature_44
- feature_46
- feature_55
- feature_59
- feature_62
- feature_66
- feature_72
- feature_75
- feature_76
- feature_78
- feature_79
- feature_83
- feature_84
- feature_87
- feature_96
- feature_100
- feature_103
- feature_112
- feature_124
- feature_126
- feature_127
- feature_133
- feature_134
- feature_141
- feature_142
- feature_145
- feature_147
- feature_148
- feature_153
- feature_157
- feature_161
- feature_162
- feature_168
- feature_183
stack_features:
- lamau_814_full_dataset
- lgb_8122_full_dataset
- cb_8114_full_dataset
- xgb_81325_full_dataset
- lama_81298_full_dataset
- lamann_autoint_8053_full_dataset
- lamann_fttransformer_8050_full_dataset
stack_selected_features:
- feature_71
- feature_12
- feature_16
- feature_20
- feature_27
- feature_53
- feature_72
- feature_124
- feature_127
- feature_157
- feature_158
- feature_171
- feature_186
- lamau_814_full_dataset
- lgb_8122_full_dataset
- cb_8114_full_dataset
- xgb_81325_full_dataset
- lama_81298_full_dataset
- lamann_autoint_8053_full_dataset
- lamann_fttransformer_8050_full_dataset
